import 'package:hive/hive.dart';

part 'student_model.g.dart'; // This file will be generated by Hive

@HiveType(typeId: 1) // Unique type ID for the student model
class StudentModel extends HiveObject {
  @HiveField(0)
  final String? uid;

  @HiveField(1)
  String? fullName;

  @HiveField(3)
  String? rollNumber;

  @HiveField(4)
  String? admissionNumber;

  @HiveField(5)
  String? dob;

  @HiveField(6)
  String? bloodGroup;

  @HiveField(7)
  String? aadharNumber;

  @HiveField(8)
  String? email;

  @HiveField(9)
  String? phoneNumber;

  @HiveField(10)
  String? residentialAddress;

  @HiveField(11)
  String? parentName;

  @HiveField(12)
  String? parentPhone;

  @HiveField(13)
  String? schoolName;

  @HiveField(14)
  String? standard;

  @HiveField(15)
  String? division;

  @HiveField(16)
  String? currentLocation;

  @HiveField(17)
  bool? isStudent = true;

  @HiveField(18)
  String? profileUrl;

  @HiveField(19)
  String? gender;

  StudentModel({
    this.uid,
    this.fullName,
    this.rollNumber,
    this.admissionNumber,
    this.dob,
    this.bloodGroup,
    this.aadharNumber,
    this.email,
    this.phoneNumber,
    this.residentialAddress,
    this.parentName,
    this.parentPhone,
    this.schoolName,
    this.standard,
    this.division,
    this.currentLocation,
    this.isStudent,
    this.profileUrl,
    this.gender,
  });

  // Convert StudentModel to Map
  Map<String, dynamic> toMap() {
    return {
      'uid': uid, // Store empty string if null
      'fullName': fullName, // Store empty string if null
      'rollNumber': rollNumber, // Store empty string if null
      'admissionNumber': admissionNumber, // Store empty string if null
      'dob': dob, // Store empty string if null
      'bloodGroup': bloodGroup, // Store empty string if null
      'aadharNumber': aadharNumber, // Store empty string if null
      'email': email, // Store empty string if null
      'phoneNumber': phoneNumber, // Store empty string if null
      'residentialAddress': residentialAddress, // Store empty string if null
      'parentName': parentName, // Store empty string if null
      'parentPhone': parentPhone, // Store empty string if null
      'schoolName': schoolName, // Store empty string if null
      'standard': standard, // Store empty string if null
      'division': division, // Store empty string if null
      'currentLocation': currentLocation, // Store empty string if null
      'isStudent': isStudent, // Store default value if null
      'profileUrl': profileUrl, // Store empty string if null
      'gender': gender, // Store empty string if null
    };
  }

  // Convert Map to StudentModel
  factory StudentModel.fromMap(Map<String, dynamic> map) {
    return StudentModel(
      uid: map['uid'] ?? '',
      fullName: map['fullName'] ?? '',
      rollNumber: map['rollNumber'] ?? '',
      admissionNumber: map['admissionNumber'] ?? '',
      dob: map['dob'] ?? '',
      bloodGroup: map['bloodGroup'] ?? '',
      aadharNumber: map['aadharNumber'] ?? '',
      email: map['email'] ?? '',
      phoneNumber: map['phoneNumber'] ?? '',
      residentialAddress: map['residentialAddress'] ?? '',
      parentName: map['parentName'] ?? '',
      parentPhone: map['parentPhone'] ?? '',
      schoolName: map['schoolName'] ?? '',
      standard: map['standard'] ?? '',
      division: map['division'] ?? '',
      currentLocation: map['currentLocation'] ?? '',
      isStudent: map['isStudent'] ?? true,
      profileUrl: map['profileUrl'] ?? '',
      gender: map['gender'] ?? '',
    );
  }
}
