import 'package:hive/hive.dart';

part 'student_model.g.dart'; // This file will be generated by Hive

@HiveType(typeId: 1) // Unique type ID for the student model
class StudentModel {
  @HiveField(0)
  final String uid;

  @HiveField(1)
  final String name;

  @HiveField(2)
  final String schoolName;

  @HiveField(3)
  final String standard; // E.g., 5th, 6th grade

  @HiveField(4)
  final String division; // E.g., A, B, C division

  @HiveField(5)
  final String phoneNumber;

  @HiveField(6)
  final String currentLocation;

  @HiveField(7)
  bool? isStudent = true;

  StudentModel({
    required this.uid,
    required this.name,
    required this.schoolName,
    required this.standard,
    required this.division,
    required this.phoneNumber,
    required this.currentLocation,
    this.isStudent,
  });
}
