import 'package:hive/hive.dart';

part 'teacher_model.g.dart'; // This file will be generated by Hive

@HiveType(typeId: 0) // Unique type ID for the teacher model
class TeacherModel {
  @HiveField(1)
  String? uid;

  @HiveField(2)
  String? fullName;

  @HiveField(3)
  String? schoolName;

  @HiveField(4)
  String? subject;

  @HiveField(5)
  String? phoneNumber;

  @HiveField(6)
  String? currentLocation;

  @HiveField(7)
  bool? isTeacher = true;

  @HiveField(8)
  String? dob;

  @HiveField(9)
  String? bloodGroup;

  @HiveField(10)
  String? aadharNumber;

  @HiveField(11)
  String? email;

  @HiveField(12)
  String? residentialAddress;

  @HiveField(13)
  String? profileUrl;

  TeacherModel({
    this.uid,
    this.fullName,
    this.schoolName,
    this.subject,
    this.phoneNumber,
    this.currentLocation,
    this.isTeacher,
    this.dob,
    this.bloodGroup,
    this.aadharNumber,
    this.email,
    this.residentialAddress,
    this.profileUrl,
  });

  // Convert TeacherModel to Map
  Map<String, dynamic> toMap() {
    return {
      'uid': uid, // Store empty string if null
      'fullName': fullName, // Store empty string if null
      'schoolName': schoolName, // Store empty string if null
      'subject': subject, // Store empty string if null
      'phoneNumber': phoneNumber, // Store empty string if null
      'currentLocation': currentLocation, // Store empty string if null
      'isTeacher': isTeacher, // Store default value if null
      'dob': dob, // Store empty string if null
      'bloodGroup': bloodGroup, // Store empty string if null
      'aadharNumber': aadharNumber, // Store empty string if null
      'email': email, // Store empty string if null
      'residentialAddress': residentialAddress, // Store empty string if null
      'profileUrl': profileUrl, // Store empty string if null
    };
  }

  // Convert Map to TeacherModel
  factory TeacherModel.fromMap(Map<String, dynamic> map) {
    return TeacherModel(
      uid: map['uid'] ?? '',
      fullName: map['fullName'] ?? '',
      schoolName: map['schoolName'] ?? '',
      subject: map['subject'] ?? '',
      phoneNumber: map['phoneNumber'] ?? '',
      currentLocation: map['currentLocation'] ?? '',
      isTeacher: map['isTeacher'] ?? true,
      dob: map['dob'] ?? '',
      bloodGroup: map['bloodGroup'] ?? '',
      aadharNumber: map['aadharNumber'] ?? '',
      email: map['email'] ?? '',
      residentialAddress: map['residentialAddress'] ?? '',
      profileUrl: map['profileUrl'] ?? '',
    );
  }
}
