import 'package:hive/hive.dart';

part 'teacher_model.g.dart'; // This file will be generated by Hive

@HiveType(typeId: 0) // Unique type ID for the teacher model
class TeacherModel {
  @HiveField(1)
  final String uid;

  @HiveField(2)
  final String name;

  @HiveField(3)
  final String schoolName; // Subjects the teacher teaches, e.g., Hindi, English

  @HiveField(4)
  final String subject;

  @HiveField(5)
  final String phoneNumber;

  @HiveField(6)
  String currentLocation;

  @HiveField(7)
  bool? isTeacher = true;

  TeacherModel({
    required this.uid,
    required this.name,
    required this.schoolName,
    required this.subject,
    required this.phoneNumber,
    required this.currentLocation,
    this.isTeacher,
  });
}
