// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChnm9SHPbDJlBFdbvkE4_Vo0KPTd9htvs',
    appId: '1:307798697619:web:d43465876330a243a50f66',
    messagingSenderId: '307798697619',
    projectId: 'campauslink',
    authDomain: 'campauslink.firebaseapp.com',
    databaseURL: 'https://campauslink-default-rtdb.firebaseio.com',
    storageBucket: 'campauslink.appspot.com',
    measurementId: 'G-7QEFGN3ERP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Rj26TFryvJOWkgHcUXZxKUpv6U521p4',
    appId: '1:307798697619:android:d383396d18040e35a50f66',
    messagingSenderId: '307798697619',
    projectId: 'campauslink',
    databaseURL: 'https://campauslink-default-rtdb.firebaseio.com',
    storageBucket: 'campauslink.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOi473nhAdleSA3ZU8EsKh4DT61yjd_bY',
    appId: '1:307798697619:ios:e5f4d702f23e29c8a50f66',
    messagingSenderId: '307798697619',
    projectId: 'campauslink',
    databaseURL: 'https://campauslink-default-rtdb.firebaseio.com',
    storageBucket: 'campauslink.appspot.com',
    androidClientId: '307798697619-6aajeh70ivfjivrcfcd9otn4ss5tr6v8.apps.googleusercontent.com',
    iosClientId: '307798697619-otjr1euesptegvqf4bj5t29d97j0lkbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.pencilo',
  );

}